{% set version = "2.1.3" %}

package:
  name: bob.core
  version: {{ version }}

source:
  fn: bob.core-{{ version }}.zip
  url: https://pypi.python.org/packages/source/b/bob.core/bob.core-{{ version }}.zip
  md5: b1d4432bf0da4a0941185c767668f563

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
  - python
  - setuptools
  - cmake
  - pkg-config
  - bob.blitz
  - boost 1.61.*

  run:
  - python
  - bob.blitz
  - boost 1.61.*

test:
  requires:
  - nose

  imports:
  - bob
  - bob.core
  - bob.core.random

  commands:
  - nosetests -sv bob.core

about:
  home: http://github.com/bioidiap/bob.core
  license: Modified BSD License (3-clause)
  summary: Logging and RNG for Bob

extra:
  recipe-maintainers:
  - 183amir
