{% set version = "2.1.4" %}

package:
  name: bob.core
  version: {{ version }}

source:
  fn: bob.core-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob.core/bob.core-{{ version }}.zip
  md5: a13a56264a8c24df189a51eadb8a7b44

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
  - python
  - setuptools
  - cmake
  - pkg-config
  - bob.blitz
  - boost 1.61.*

  run:
  - python
  - bob.blitz
  - boost 1.61.*

test:
  requires:
  - nose

  imports:
  - bob
  - bob.core
  - bob.core.random

  commands:
  - nosetests -sv bob.core

about:
  home: https://www.idiap.ch/software/bob/
  license: Modified BSD License (3-clause)
  summary: Logging and RNG for Bob

extra:
  recipe-maintainers:
  - 183amir
